allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@swc/core': false
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: false
  workerd: set this to true or false
