allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': set this to true or false
  esbuild: true
  msgpackr-extract: set this to true or false
  prisma: set this to true or false
  unrs-resolver: false
  workerd: set this to true or false
