export const DomainErrorCode = {
  // General
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  CONFLICT: 'CONFLICT',
  NOT_FOUND: 'NOT_FOUND',

  // User
  USER_ALREADY_SUSPENDED: 'USER_ALREADY_SUSPENDED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_CANNOT_BE_ACTIVATED: 'USER_CANNOT_BE_ACTIVATED',

  // Auth account
  AUTH_ACCOUNT_ALREADY_SUSPENDED: 'AUTH_ACCOUNT_ALREADY_SUSPENDED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_CANNOT_VERIFY_EMAIL:
    'AUTH_ACCOUNT_CANNOT_VERIFY_EMAIL',

  // TOTP
  TOTP_ALREADY_ENABLED: 'TOTP_ALREADY_ENABLED',
  TOTP_NOT_ENABLED: 'TOTP_NOT_ENABLED',

  // Verification
  VERIFICATION_NOT_PENDING: 'VERIFICATION_NOT_PENDING',
  VERIFICATION_EXPIRED: 'VERIFICATION_EXPIRED',
  VERIFICATION_MAX_ATTEMPTS_EXCEEDED:
    'VERIFICATION_MAX_ATTEMPTS_EXCEEDED',
  INVALID_VERIFICATION_VALUE: 'INVALID_VERIFICATION_VALUE',

  // Session
  SESSION_ALREADY_REVOKED: 'SESSION_ALREADY_REVOKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
} as const;

export type DomainErrorCode =
  (typeof DomainErrorCode)[keyof typeof DomainErrorCode];