version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: eduvia-redis
    ports:
      - '6379:6379'
    networks:
      - eduvia-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  eduvia-network:
    driver: bridge

volumes:
  redis_data:
